USE ROLE sysadmin;

/*--
• database, schema, warehouse and stage creation
--*/

-- create demo database
CREATE OR REPLACE DATABASE cortex_analyst_demo;

-- create schema
CREATE OR REPLACE SCHEMA revenue_timeseries;

-- create warehouse
CREATE OR REPLACE WAREHOUSE cortex_analyst_wh
    WAREHOUSE_SIZE = 'X-Small'
    WAREHOUSE_TYPE = 'standard'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
COMMENT = 'warehouse for cortex analyst demo';


USE WAREHOUSE coe_practise_wh;

CREATE STAGE raw_data DIRECTORY = (ENABLE = TRUE);

/*--
• table creation
--*/
CREATE OR REPLACE TABLE CORTEX_ANALYST_DEMO.REVENUE_TIMESERIES.DAILY_REVENUE (
	DATE DATE,
	REVENUE FLOAT,
	COGS FLOAT,
	FORECASTED_REVENUE FLOAT
);

CREATE OR REPLACE TABLE CORTEX_ANALYST_DEMO.REVENUE_TIMESERIES.DAILY_REVENUE_BY_PRODUCT (
	DATE DATE,
	PRODUCT_LINE VARCHAR(16777216),
	REVENUE FLOAT,
	COGS FLOAT,
	FORECASTED_REVENUE FLOAT
);

CREATE OR REPLACE TABLE CORTEX_ANALYST_DEMO.REVENUE_TIMESERIES.DAILY_REVENUE_BY_REGION (
	DATE DATE,
	SALES_REGION VARCHAR(16777216),
	REVENUE FLOAT,
	COGS FLOAT,
	FORECASTED_REVENUE FLOAT
);

list @raw_data;





show users like 'KARTHIK%';

alter user KARTHIKRAMAN set mins_to_unlock = 0;
alter user KARTHIKRAMAN set;

select current_timestamp;


2024-10-16 00:30:28.679 -0700;

show tables;

drop table DAILY_REVENUE;
drop table DAILY_REVENUE_BY_PRODUCT;
drop table DAILY_REVENUE_BY_REGION;

create table DAILY_REVENUE clone CORTEX_ANALYST_KAVYA.REVENUE_TIMESERIES_KAVYA.DAILY_REVENUE;
create table DAILY_REVENUE_BY_PRODUCT clone CORTEX_ANALYST_KAVYA.REVENUE_TIMESERIES_KAVYA.DAILY_REVENUE_BY_PRODUCT;
create table DAILY_REVENUE_BY_REGION clone CORTEX_ANALYST_KAVYA.REVENUE_TIMESERIES_KAVYA.DAILY_REVENUE_BY_REGION;



