use snowflake.account_usage;

select * from metering_daily_history limit 10;
/* Generated by Snowflake Copilot */
SELECT
  SUM(metering_daily_history.credits_used) AS total_cost
FROM
  metering_daily_history
WHERE
  DATE_PART (YEAR, metering_daily_history.usage_date) = DATE_PART (YEAR, CURRENT_DATE);
/* Generated by Snowflake Copilot */
SELECT
  warehouse_name,
  SUM(credits_used) AS total_credits_used
FROM
  warehouse_metering_history
WHERE
  DATE_PART (YEAR, start_time) = DATE_PART (YEAR, CURRENT_DATE)
GROUP BY
  warehouse_name;
/* Generated by Snowflake Copilot */
SELECT
  warehouse_name,
  SUM(credits_used) AS total_credits_used
FROM
  warehouse_metering_history
WHERE
  DATE_PART (YEAR, start_time) = DATE_PART (YEAR, CURRENT_DATE)
GROUP BY
  warehouse_name;
/* Generated by Snowflake Copilot */
SELECT
  SUM(
    database_storage_usage_history.average_database_bytes
  ) AS total_storage
FROM
  database_storage_usage_history
WHERE
  DATE_PART (YEAR, database_storage_usage_history.usage_date) = DATE_PART (YEAR, CURRENT_DATE);
/* Generated by Snowflake Copilot */
SELECT
  warehouse_events_history.warehouse_name,
  COUNT(*) AS utilization_count
FROM
  warehouse_events_history
WHERE
  warehouse_events_history.event_state = 'Utilization'
GROUP BY
  warehouse_events_history.warehouse_name
ORDER BY
  utilization_count DESC
LIMIT
  10;
/* Generated by Snowflake Copilot */
SELECT
  warehouse_events_history.warehouse_name,
  COUNT(*) AS utilization_count
FROM
  warehouse_events_history
WHERE
  warehouse_events_history.event_state = 'Utilization'
GROUP BY
  warehouse_events_history.warehouse_name
ORDER BY
  utilization_count ASC
LIMIT
  10;


  select distinct 
  event_state from warehouse_events_history ;



  SELECT
  query_history.query_id,
  query_history.query_text,
  (
    query_history.end_time - query_history.start_time
  ) AS duration
FROM
  query_history
GROUP BY
  query_history.query_id,
  query_history.query_text
ORDER BY
  duration DESC
LIMIT
  10;


  show users;

  use database coe_practise_db;
  use schema manimaranc;


select get_ddl('procedure','PRC_MONITOR_CONSUMPTION_DAILY(VARCHAR)');


CREATE OR REPLACE PROCEDURE "PRC_MONITOR_CONSUMPTION_DAILY"("P_EMAIL" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS '
var result;
var mail_body;
 
/*-----------------------------------------------------------------------------------------------*
*                    PROCEDURE_FOR_ALERTS                                             *
*------------------------------------------------------------------------------------------------*
*  Author:          Manimaran                                                                   *
*  Date:            11-Jan-2023                                                                    *
*  Final Procedure Name: PRC_DAILY_TIME_ELASPSED_NOTIFY                                       *
**************************************************************************************************
*                                  Modification History                                          *
**************************************************************************************************
*  Version#     Date               EID          Description                                      *
*  01           11-Jan-2023        H529007      Initial version                                  *
*-----------------------------------------------------------------------------------------------*/
 

 
  var sql_query=`with
  daily as (select TO_DATE(usage_date) usage_date,round(sum(usage_in_currency),2) actual_consumption from snowflake.organization_usage.usage_in_currency_daily
where usage_date >= date(current_date) -9
group by all)
select usage_date, actual_consumption, 7542.55 as ideal_consumption, round(7542.55 - actual_consumption,2) as difference 
  from daily
order by 1 desc;`
 
 
  var sql_smt=snowflake.createStatement({sqlText: sql_query});
   var result_daily=sql_smt.execute();
   var table_html;
  table_html = `<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>
<title>Montior Daily Consumption</title>
</head>
<body>

<h1>Consumption Across Organization</h1>
<p>Remaining Balance :_remaining_balance</p>
<table style="width:100%">
  <tr>
    <th>Date</th>
    <th>Actual Consumption$</th>
    <th>Ideal Consumption$</th>
    <th>Difference$</th>
  </tr>`;

   if (result_daily.getRowCount()>0)
{
while(result_daily.next())
{
 table_html += "<tr><td>"+ result_daily.getColumnValue(1) +"</td>";
 table_html += "<td>"+ result_daily.getColumnValue(2) +"</td>";
 table_html += "<td>"+ result_daily.getColumnValue(3) +"</td>";
 table_html += "<td>"+ result_daily.getColumnValue(4) +"</td></tr>";
 
}
}
else 
{
return "No record";
}

table_html += "</table></body></html>";

  

var sql_query_bln=`select CAPACITY_BALANCE from snowflake.organization_usage.remaining_balance_daily
where date = current_date()
;`
 
 
  var sql_smt_bln=snowflake.createStatement({sqlText: sql_query_bln});
   var result_bln=sql_smt_bln.execute();
   result_bln.next();

  
  
  var remaining_balance = String(result_bln.getColumnValue(1));

  var mail_body = table_html.replace("_remaining_balance", remaining_balance);

  

 return mail_body;
  var mail_stmt_4= `call system$send_email(
  ''Email_Notification_Integration'',
   ''`+ P_EMAIL + `'',
  ''Snowflake Alert: Queries elapsed for 4 hours'',
  ''Results: \\n `+ mail_body + `'',
  ''text/html''
  );`


 
  var mail_query_10=snowflake.createStatement({sqlText: mail_stmt_4});
  mail_query_10.execute();
  return ''Done''
 

 

 
 
';

select * from snowflake.account_usage.users;

show parameters for users;

use database snowflake;
use role accountadmin;
show schemas;
use schema DATA_PRIVACY;
show views;

select class_name,count(*) from SNOWFLAKE.ACCOUNT_USAGE.CLASS_INSTANCES 
group by all;


SELECT * 
  FROM SNOWFLAKE.ACCOUNT_USAGE.CLASSES limit 10;

  select * from COMPUTE_POOLS;

  select * From DATA_CLASSIFICATION_LATEST limit 10;

  select * From DATA_METRIC_FUNCTION_REFERENCES limit 10;

  select * from ELEMENT_TYPES;

  show tags in account;

  select *
  from table(snowflake.account_usage.tag_references_with_lineage('coe_practise_db.manimaranc.metadata_sflk'));


 SELECT * FROM TABLE(RESULT_SCAN(SNOWFLAKE.ALERT.GET_CONDITION_QUERY_UUID()));


 SELECT SNOWFLAKE.CORE.DUPLICATE_COUNT(
  select event_timestamp from coe_practise_db.manimaranc.LOGIN_HISTORY
);

show tables in schema coe_practise_db.manimaranc;

select * from coe_practise_db.manimaranc.LOGIN_HISTORY limit 10;

SELECT SNOWFLAKE.CORE.unique_count(
  select user_name from coe_practise_db.manimaranc.LOGIN_HISTORY
)-- < 300
;

SELECT SNOWFLAKE.CORTEX.COMPLETE('snowflake-arctic', 'How to implement Schema Contracts in Snowflake');

SELECT SNOWFLAKE.CORTEX.EMBED_TEXT_1024('nv-embed-qa-4', 'Snowflake AI Cloud');

SELECT SNOWFLAKE.CORTEX.TRANSLATE('Bose’s goal in developing the new Ultra Open Earbuds was to create a pair of earbuds that you can truly wear all day. With a design that attaches to the side of your ears instead of going inside them, they’re anything but conventional. Bose released some impressive new products last year, but in the grand scheme of things, they were all fairly iterative. The Ultra Open Earbuds represent the biggest swing the company has taken in a long time. Will they go down as another short-term experiment like the SoundWear Companion or Bose Frames? Or, as Bose certainly hopes, are these a peek at the future of wearable tech?
I don’t think there’s a simple answer. These unorthodox earbuds won’t be for everyone, and their premium $299 price immediately puts them out of range for many shoppers. Speaking for myself, someone who is happy to plug up his ear canals with high-quality buds in the name of sublime audio, I’m not the target market. The Ultra Open Earbuds are for people who want to maintain awareness of their surroundings at all times; their design fundamentally means you will always hear external noise — and you’ll hear it naturally, at full volume. Whether you’re riding a bike, out for a run, working in an environment where regular earbuds aren’t practical, or just find the whole in-ear concept to be uncomfortable, these allow you to go about your day, stay fully alert, and jam along to a soundtrack the whole time.','en','ja');


    SELECT SNOWFLAKE.CORTEX.SENTIMENT(review_content), review_content FROM reviews LIMIT 10;

    SELECT SNOWFLAKE.CORTEX.COUNT_TOKENS( 'snowflake-arctic', 'What is the significance of AI in future' );


SELECT res.* from METERING_DAILY_HISTORY, TABLE(
  SNOWFLAKE.ML.TOP_INSIGHTS(
    service_type,
    usage_date,
    credits_billed,
   'Credit Summary'
  )
  OVER (PARTITION BY 0)
) res
ORDER BY res.surprise DESC;


SELECT res.* from input, TABLE(
  SNOWFLAKE.ML.TOP_INSIGHTS(
    input.categorical_dimensions,
    input.continuous_dimensions,
    CAST(input.metric AS FLOAT),
    input.label
  )
  OVER (PARTITION BY 0)
) res ORDER BY res.surprise DESC;

show views;

select * from snowflake.account_usage.METERING_DAILY_HISTORY limit 10;


use schema coe_practise_db.manimaranc;

create or replace table METERING_DAILY_HISTORY as select * from METERING_DAILY_HISTORY;

create view METERING_DAILY_HISTORY_VW as select * from METERING_DAILY_HISTORY;

select get_ddl('view','METERING_DAILY_HISTORY_VW');



CREATE SNOWFLAKE.ML.FORECAST MH_Forecast_model(
  INPUT_DATA => TABLE(METERING_DAILY_HISTORY_VW),
  TIMESTAMP_COLNAME => 'usage_date',
  TARGET_COLNAME => 'credits_billed'
);

-- Generate forecasts using your model
SELECT * FROM TABLE(MH_Forecast_model!FORECAST(FORECASTING_PERIODS => 7));

call MH_Forecast_model!FORECAST(FORECASTING_PERIODS => 3);

drop view ;

create or replace view METERING_DAILY_HISTORY_VW(
	SERVICE_TYPE,
	USAGE_DATE,
	CREDITS_USED_COMPUTE,
	CREDITS_USED_CLOUD_SERVICES,
	CREDITS_USED,
	CREDITS_ADJUSTMENT_CLOUD_SERVICES,
	CREDITS_BILLED
) as select SERVICE_TYPE,
	to_timestamp(USAGE_DATE),
	CREDITS_USED_COMPUTE,
	CREDITS_USED_CLOUD_SERVICES,
	CREDITS_USED,
	CREDITS_ADJUSTMENT_CLOUD_SERVICES,
	CREDITS_BILLED from METERING_DAILY_HISTORY;